Import Extension from setuptools instead of Cython
Fixes error:

```
error: each element of 'ext_modules' option must be an Extension
instance or 2-tuple
```